const dataCards = [
  {
    id: 1,
    href: `#`,
    src: `img/apartment-01.jpg`,
    isPremium: true,
    price: 120,
    title: `Beautiful &amp; luxurious apartment at great location`,
    placeType: `Apartment`,
    isFavorite: false,
    rating: 4,
  },
  {
    id: 2,
    href: `#`,
    src: `img/room.jpg`,
    isPremium: false,
    price: 80,
    title: `Wood and stone place`,
    placeType: `Private room`,
    isFavorite: true,
    rating: 4,
  },
  {
    id: 3,
    href: `#`,
    src: `img/apartment-02.jpg`,
    isPremium: false,
    price: 132,
    title: `Canal View Prinsengracht`,
    placeType: `Apartment`,
    isFavorite: false,
    rating: 4,
  },
  {
    id: 4,
    href: `#`,
    src: `img/apartment-03.jpg`,
    isPremium: true,
    price: 180,
    title: `Nice, cozy, warm big bed apartment`,
    placeType: `Apartment`,
    isFavorite: false,
    rating: 5,
  },
  {
    id: 5,
    href: `#`,
    src: `img/room.jpg`,
    isPremium: false,
    price: 80,
    title: `Wood and stone place`,
    placeType: `Private room`,
    isFavorite: true,
    rating: 4,
  },
];

export {dataCards};
